name: Build

on:
  push:
    branches:
      - 'test/*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - 'test-[a-zA-Z0-9]+'

env:
  DOCKER_META_IMAGES: |
    ghcr.io/imgproxy/imgproxy-base
  DOCKER_META_TAGS: |
    type=semver,pattern=v{{version}}
    type=ref,event=branch,enable=${{ startsWith(github.ref, 'refs/heads/test/') }}

jobs:
  # Get the latest tag to determine if the current build is for the latest version.
  # This is needed to decide whether to push the "latest" tag for the current build.
  is-latest-tag:
    if: github.repository_owner == 'imgproxy'
    runs-on: ubuntu-latest
    outputs:
      is-latest: ${{ steps.get-latest-tag.outputs.result }}
    permissions:
      contents: read
    steps:
      - name: Get the latest tag
        id: get-latest-tag
        uses: actions/github-script@v9
        with:
          script: |
            const { data: tags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });

            const latestTag = tags.find(tag => /^v\d+\.\d+\.\d+$/.test(tag.name));
            const currentTag = context.ref.replace('refs/tags/', '');

            return latestTag ? currentTag === latestTag.name : false;

  build:
    if: github.repository_owner == 'imgproxy'
    needs: is-latest-tag
    strategy:
      matrix:
        build:
          - arch: amd64
            dockerPlatform: linux/amd64
            image: linux-5.0
          - arch: arm64
            dockerPlatform: linux/arm64/v8
            image: arm-3.0
    runs-on:
      - codebuild-imgproxy-${{ github.run_id }}-${{ github.run_attempt }}
      - image:${{ matrix.build.image }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_META_IMAGES }}
          tags: ${{ env.DOCKER_META_TAGS }}
          flavor: |
            latest=${{ needs.is-latest-tag.outputs.is-latest }}
            suffix=-${{ matrix.build.arch }},onlatest=true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.build.dockerPlatform }}
          provenance: false
          push: true

  push_manifests:
    needs: [is-latest-tag, build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_META_IMAGES }}
          tags: ${{ env.DOCKER_META_TAGS }}
          flavor: |
            latest=${{ needs.is-latest-tag.outputs.is-latest }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push manifests
        run: |
          for tag in ${{ join(fromJSON(steps.meta.outputs.json).tags, ' ') }}
          do
            docker buildx imagetools create -t $tag ${tag}-amd64 ${tag}-arm64
          done

